version: "2.2"
services:
  app:
    container_name: doozez-trnx
    environment:
      - NODE_ENV=development
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"