version: "2.2"
services:
  app:
    container_name: doozez-bender
    environment:
      - NODE_ENV=development
    restart: always
    image: doozez-bender:202005301236
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"