apiVersion: apps/v1
kind: Deployment
metadata:
  name: bender-deployment
  labels:
    app: bender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bender
  template:
    metadata:
      labels:
        app: bender
    spec:
      containers:
      - name: bender
        image: doozez/bender:1.0.0
        ports:
        - containerPort: 80